# fly.toml app configuration file generated for employee-creator1 on 2023-08-31T15:59:49+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "employee-creator1"
primary_region = "syd"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
